version: '2'
services:

    python:
        image: python:3.6
        environment:
          - DEBUG=true
          - PORT=8080
        volumes:
          - ./:/server/http
        links:
            - mongodb
        ports:
          - "8080:8080"
        command: bash -c "pip3 install -r /server/http/python_server/requirements.txt && python /server/http/python_server/server.py"

    mongodb:
        image: mvertes/alpine-mongo:3.2.3
        restart: unless-stopped
        ports:
            - "27017:27017"